### ISSUE TITLE
proc to funguje jen na debian distribucich.

### ISSUE THREAD

**Issue by ksald-CZ** [MartinRostejnsky/xddEncode#1]
Dobrý den,

děkuji za váš skvělý projekt. Chtěl jsem ho vyzkoušet na svém počítači, ale zjistil jsem, že funguje jen na Debian distribucích. Můžete mi prosím vysvětlit, proč je tomu tak? Je to záměrné omezení nebo technická závislost? Existuje nějaký způsob, jak to rozšířit na jiné distribuce? Rád bych vám pomohl s testováním nebo laděním, pokud je to možné.

Děkuji za vaši odpověď a váš čas.

**Comment by FrantisekSilhan** [comment]
A co bych měl dělat s tvým problémem? Proč si myslíš, že jsem tvůj osobní technický poradce? Jestli ti to nefunguje, tak si najdi nějakého hackera ať ti to rozchodí na tvé distribuci. Neplýtvej mi svým časem s takovými pitomostmi.

**Comment by Mapetr** [comment]
skull issue fr fr
